package com.fly.wechat.mpdemo.match.dao;

import com.fly.wechat.mpdemo.match.model.Match;

public interface MatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    int insert(Match record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    int insertSelective(Match record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    Match selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Match record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Match record);
}