package com.fly.wechat.mpdemo.match.dao;

import com.fly.wechat.mpdemo.match.model.MatchTeam;

public interface MatchTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    int insert(MatchTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    int insertSelective(MatchTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    MatchTeam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MatchTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_team
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MatchTeam record);
}