package com.fly.wechat.mpdemo.match.dao;

import com.fly.wechat.mpdemo.match.model.TeamPlayer;

public interface TeamPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    int insert(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    int insertSelective(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    TeamPlayer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeamPlayer record);
}