package com.fly.wechat.mpdemo.match.model;

import java.util.Date;

public class GamePlayerDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.game_id
     *
     * @mbggenerated
     */
    private Long gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.player_id
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.sf
     *
     * @mbggenerated
     */
    private Byte sf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.num
     *
     * @mbggenerated
     */
    private Byte num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.min
     *
     * @mbggenerated
     */
    private Byte min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.fg
     *
     * @mbggenerated
     */
    private Byte fg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.fgt
     *
     * @mbggenerated
     */
    private Byte fgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.pt3
     *
     * @mbggenerated
     */
    private Byte pt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.pt3t
     *
     * @mbggenerated
     */
    private Byte pt3t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.ft
     *
     * @mbggenerated
     */
    private Byte ft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.ftt
     *
     * @mbggenerated
     */
    private Byte ftt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.oreb
     *
     * @mbggenerated
     */
    private Byte oreb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.dreb
     *
     * @mbggenerated
     */
    private Byte dreb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.reb
     *
     * @mbggenerated
     */
    private Byte reb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.ast
     *
     * @mbggenerated
     */
    private Byte ast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.stl
     *
     * @mbggenerated
     */
    private Byte stl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.blk
     *
     * @mbggenerated
     */
    private Byte blk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.to
     *
     * @mbggenerated
     */
    private Byte to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.pf
     *
     * @mbggenerated
     */
    private Byte pf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.pts
     *
     * @mbggenerated
     */
    private Byte pts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_player_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.id
     *
     * @return the value of game_player_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.id
     *
     * @param id the value for game_player_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.game_id
     *
     * @return the value of game_player_detail.game_id
     *
     * @mbggenerated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.game_id
     *
     * @param gameId the value for game_player_detail.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.team_id
     *
     * @return the value of game_player_detail.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.team_id
     *
     * @param teamId the value for game_player_detail.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.player_id
     *
     * @return the value of game_player_detail.player_id
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.player_id
     *
     * @param playerId the value for game_player_detail.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.sf
     *
     * @return the value of game_player_detail.sf
     *
     * @mbggenerated
     */
    public Byte getSf() {
        return sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.sf
     *
     * @param sf the value for game_player_detail.sf
     *
     * @mbggenerated
     */
    public void setSf(Byte sf) {
        this.sf = sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.num
     *
     * @return the value of game_player_detail.num
     *
     * @mbggenerated
     */
    public Byte getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.num
     *
     * @param num the value for game_player_detail.num
     *
     * @mbggenerated
     */
    public void setNum(Byte num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.min
     *
     * @return the value of game_player_detail.min
     *
     * @mbggenerated
     */
    public Byte getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.min
     *
     * @param min the value for game_player_detail.min
     *
     * @mbggenerated
     */
    public void setMin(Byte min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.fg
     *
     * @return the value of game_player_detail.fg
     *
     * @mbggenerated
     */
    public Byte getFg() {
        return fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.fg
     *
     * @param fg the value for game_player_detail.fg
     *
     * @mbggenerated
     */
    public void setFg(Byte fg) {
        this.fg = fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.fgt
     *
     * @return the value of game_player_detail.fgt
     *
     * @mbggenerated
     */
    public Byte getFgt() {
        return fgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.fgt
     *
     * @param fgt the value for game_player_detail.fgt
     *
     * @mbggenerated
     */
    public void setFgt(Byte fgt) {
        this.fgt = fgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.pt3
     *
     * @return the value of game_player_detail.pt3
     *
     * @mbggenerated
     */
    public Byte getPt3() {
        return pt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.pt3
     *
     * @param pt3 the value for game_player_detail.pt3
     *
     * @mbggenerated
     */
    public void setPt3(Byte pt3) {
        this.pt3 = pt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.pt3t
     *
     * @return the value of game_player_detail.pt3t
     *
     * @mbggenerated
     */
    public Byte getPt3t() {
        return pt3t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.pt3t
     *
     * @param pt3t the value for game_player_detail.pt3t
     *
     * @mbggenerated
     */
    public void setPt3t(Byte pt3t) {
        this.pt3t = pt3t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.ft
     *
     * @return the value of game_player_detail.ft
     *
     * @mbggenerated
     */
    public Byte getFt() {
        return ft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.ft
     *
     * @param ft the value for game_player_detail.ft
     *
     * @mbggenerated
     */
    public void setFt(Byte ft) {
        this.ft = ft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.ftt
     *
     * @return the value of game_player_detail.ftt
     *
     * @mbggenerated
     */
    public Byte getFtt() {
        return ftt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.ftt
     *
     * @param ftt the value for game_player_detail.ftt
     *
     * @mbggenerated
     */
    public void setFtt(Byte ftt) {
        this.ftt = ftt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.oreb
     *
     * @return the value of game_player_detail.oreb
     *
     * @mbggenerated
     */
    public Byte getOreb() {
        return oreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.oreb
     *
     * @param oreb the value for game_player_detail.oreb
     *
     * @mbggenerated
     */
    public void setOreb(Byte oreb) {
        this.oreb = oreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.dreb
     *
     * @return the value of game_player_detail.dreb
     *
     * @mbggenerated
     */
    public Byte getDreb() {
        return dreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.dreb
     *
     * @param dreb the value for game_player_detail.dreb
     *
     * @mbggenerated
     */
    public void setDreb(Byte dreb) {
        this.dreb = dreb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.reb
     *
     * @return the value of game_player_detail.reb
     *
     * @mbggenerated
     */
    public Byte getReb() {
        return reb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.reb
     *
     * @param reb the value for game_player_detail.reb
     *
     * @mbggenerated
     */
    public void setReb(Byte reb) {
        this.reb = reb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.ast
     *
     * @return the value of game_player_detail.ast
     *
     * @mbggenerated
     */
    public Byte getAst() {
        return ast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.ast
     *
     * @param ast the value for game_player_detail.ast
     *
     * @mbggenerated
     */
    public void setAst(Byte ast) {
        this.ast = ast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.stl
     *
     * @return the value of game_player_detail.stl
     *
     * @mbggenerated
     */
    public Byte getStl() {
        return stl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.stl
     *
     * @param stl the value for game_player_detail.stl
     *
     * @mbggenerated
     */
    public void setStl(Byte stl) {
        this.stl = stl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.blk
     *
     * @return the value of game_player_detail.blk
     *
     * @mbggenerated
     */
    public Byte getBlk() {
        return blk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.blk
     *
     * @param blk the value for game_player_detail.blk
     *
     * @mbggenerated
     */
    public void setBlk(Byte blk) {
        this.blk = blk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.to
     *
     * @return the value of game_player_detail.to
     *
     * @mbggenerated
     */
    public Byte getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.to
     *
     * @param to the value for game_player_detail.to
     *
     * @mbggenerated
     */
    public void setTo(Byte to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.pf
     *
     * @return the value of game_player_detail.pf
     *
     * @mbggenerated
     */
    public Byte getPf() {
        return pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.pf
     *
     * @param pf the value for game_player_detail.pf
     *
     * @mbggenerated
     */
    public void setPf(Byte pf) {
        this.pf = pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.pts
     *
     * @return the value of game_player_detail.pts
     *
     * @mbggenerated
     */
    public Byte getPts() {
        return pts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.pts
     *
     * @param pts the value for game_player_detail.pts
     *
     * @mbggenerated
     */
    public void setPts(Byte pts) {
        this.pts = pts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_player_detail.create_time
     *
     * @return the value of game_player_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_player_detail.create_time
     *
     * @param createTime the value for game_player_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}