package com.fly.wechat.mpdemo.match.model;

import java.util.Date;

public class Game {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.match_id
     *
     * @mbggenerated
     */
    private Long matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.aid
     *
     * @mbggenerated
     */
    private Long aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.bid
     *
     * @mbggenerated
     */
    private Long bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.ascore
     *
     * @mbggenerated
     */
    private Integer ascore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.bscore
     *
     * @mbggenerated
     */
    private Integer bscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.ascore_detail
     *
     * @mbggenerated
     */
    private String ascoreDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.bscore_detail
     *
     * @mbggenerated
     */
    private String bscoreDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.game_didian
     *
     * @mbggenerated
     */
    private String gameDidian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.game_time
     *
     * @mbggenerated
     */
    private Date gameTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.id
     *
     * @return the value of game.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.id
     *
     * @param id the value for game.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.match_id
     *
     * @return the value of game.match_id
     *
     * @mbggenerated
     */
    public Long getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.match_id
     *
     * @param matchId the value for game.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(Long matchId) {
        this.matchId = matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.name
     *
     * @return the value of game.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.name
     *
     * @param name the value for game.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.aid
     *
     * @return the value of game.aid
     *
     * @mbggenerated
     */
    public Long getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.aid
     *
     * @param aid the value for game.aid
     *
     * @mbggenerated
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.bid
     *
     * @return the value of game.bid
     *
     * @mbggenerated
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.bid
     *
     * @param bid the value for game.bid
     *
     * @mbggenerated
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.ascore
     *
     * @return the value of game.ascore
     *
     * @mbggenerated
     */
    public Integer getAscore() {
        return ascore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.ascore
     *
     * @param ascore the value for game.ascore
     *
     * @mbggenerated
     */
    public void setAscore(Integer ascore) {
        this.ascore = ascore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.bscore
     *
     * @return the value of game.bscore
     *
     * @mbggenerated
     */
    public Integer getBscore() {
        return bscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.bscore
     *
     * @param bscore the value for game.bscore
     *
     * @mbggenerated
     */
    public void setBscore(Integer bscore) {
        this.bscore = bscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.ascore_detail
     *
     * @return the value of game.ascore_detail
     *
     * @mbggenerated
     */
    public String getAscoreDetail() {
        return ascoreDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.ascore_detail
     *
     * @param ascoreDetail the value for game.ascore_detail
     *
     * @mbggenerated
     */
    public void setAscoreDetail(String ascoreDetail) {
        this.ascoreDetail = ascoreDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.bscore_detail
     *
     * @return the value of game.bscore_detail
     *
     * @mbggenerated
     */
    public String getBscoreDetail() {
        return bscoreDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.bscore_detail
     *
     * @param bscoreDetail the value for game.bscore_detail
     *
     * @mbggenerated
     */
    public void setBscoreDetail(String bscoreDetail) {
        this.bscoreDetail = bscoreDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.game_didian
     *
     * @return the value of game.game_didian
     *
     * @mbggenerated
     */
    public String getGameDidian() {
        return gameDidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.game_didian
     *
     * @param gameDidian the value for game.game_didian
     *
     * @mbggenerated
     */
    public void setGameDidian(String gameDidian) {
        this.gameDidian = gameDidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.game_time
     *
     * @return the value of game.game_time
     *
     * @mbggenerated
     */
    public Date getGameTime() {
        return gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.game_time
     *
     * @param gameTime the value for game.game_time
     *
     * @mbggenerated
     */
    public void setGameTime(Date gameTime) {
        this.gameTime = gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.create_time
     *
     * @return the value of game.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.create_time
     *
     * @param createTime the value for game.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}