package com.fly.wechat.mpdemo.match.model;

public class MatchTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_team.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_team.match_id
     *
     * @mbggenerated
     */
    private Long matchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_team.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_team.point
     *
     * @mbggenerated
     */
    private String point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_team.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_team.id
     *
     * @return the value of match_team.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_team.id
     *
     * @param id the value for match_team.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_team.match_id
     *
     * @return the value of match_team.match_id
     *
     * @mbggenerated
     */
    public Long getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_team.match_id
     *
     * @param matchId the value for match_team.match_id
     *
     * @mbggenerated
     */
    public void setMatchId(Long matchId) {
        this.matchId = matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_team.team_id
     *
     * @return the value of match_team.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_team.team_id
     *
     * @param teamId the value for match_team.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_team.point
     *
     * @return the value of match_team.point
     *
     * @mbggenerated
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_team.point
     *
     * @param point the value for match_team.point
     *
     * @mbggenerated
     */
    public void setPoint(String point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_team.status
     *
     * @return the value of match_team.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_team.status
     *
     * @param status the value for match_team.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}