package com.fly.wechat.mpdemo.match.model;

public class TeamPlayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_player.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_player.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_player.player_id
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_player.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_player.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_player.id
     *
     * @return the value of team_player.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_player.id
     *
     * @param id the value for team_player.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_player.team_id
     *
     * @return the value of team_player.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_player.team_id
     *
     * @param teamId the value for team_player.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_player.player_id
     *
     * @return the value of team_player.player_id
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_player.player_id
     *
     * @param playerId the value for team_player.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_player.num
     *
     * @return the value of team_player.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_player.num
     *
     * @param num the value for team_player.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_player.status
     *
     * @return the value of team_player.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_player.status
     *
     * @param status the value for team_player.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}